use std::path::{Path, PathBuf};
use std::sync::Arc;

use mct_core::LanguageRegistry;
use mct_index::{ExcludeSet, Index};
use clap::{Parser, Subcommand};

/// Index a repository and inspect the index from the command line.
///
/// The MCP server (`mct-mcp-server`) does the same indexing automatically at
/// startup — this CLI is for manual/scripted use (CI, a pre-commit hook, or
/// just checking coverage before wiring up the plugin).
#[derive(Parser, Debug)]
#[command(name = "mct-cli", version, after_help = "\
Invoked here via `cargo run -p mct-cli --`; once installed on PATH (e.g.
`cargo install --path crates/mct-cli`) the binary is `mct-cli` too, so drop
the `cargo run -p mct-cli --` prefix from every example below.

Typical first run:
  cargo run -p mct-cli -- --root . init
  cargo run -p mct-cli -- --root . ignore-init --import-gitignore
  cargo run -p mct-cli -- --root . gitignore-init
  cargo run -p mct-cli -- --root . status

Run `cargo run -p mct-cli -- <command> --help` for a command's full
description and examples.")]
struct Cli {
    /// Project root to operate on. Defaults to the current working directory.
    #[arg(long, global = true)]
    root: Option<PathBuf>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Build the index for the first time.
    ///
    /// Equivalent to `reindex` — kept as a separate, discoverable first
    /// command for a fresh checkout.
    #[command(after_help = "Example:\n  cargo run -p mct-cli -- --root . init")]
    Init,
    /// Re-scan the project and update the index.
    ///
    /// Only re-parses files that changed since the last run, unless
    /// `--force` is given. Safe to run repeatedly (e.g. from a pre-commit
    /// hook or CI step) — a no-op reindex costs one blob-hash comparison
    /// per file.
    #[command(after_help = "Examples:\n  cargo run -p mct-cli -- --root . reindex\n  cargo run -p mct-cli -- --root . reindex --force")]
    Reindex {
        /// Re-parse every supported file, even if unchanged since last run.
        #[arg(long)]
        force: bool,
    },
    /// Report index health.
    ///
    /// Prints coverage per language, the last indexed time, any unsupported
    /// languages seen while walking the tree, and files that failed to
    /// parse. Run this after `init`/`reindex` to sanity-check the result,
    /// or on its own to check whether the index looks stale.
    #[command(after_help = "Example:\n  cargo run -p mct-cli -- --root . status")]
    Status,
    /// Write (or update) `.mcp.json` so an MCP client can launch this server.
    ///
    /// Writes (or updates) `.mcp.json` at the project root so Claude Code
    /// (or any other client reading that file) can launch `mct-mcp-server`
    /// for this project. Merges into an existing file instead of
    /// overwriting it, so other servers already configured there are left
    /// untouched.
    #[command(after_help = "Examples:\n  cargo run -p mct-cli -- --root . mcp-register\n  cargo run -p mct-cli -- --root . mcp-register --name my-project")]
    McpRegister {
        /// Server name (the key under `mcpServers`). Defaults to the root
        /// directory's own name.
        #[arg(long)]
        name: Option<String>,
    },
    /// Write a starter `.mctignore` for custom indexing exclusions.
    ///
    /// Writes a starter `.mctignore` at the project root, if one doesn't
    /// already exist. Lets a project exclude extra files/directories from
    /// indexing (e.g. `docs/`, `*.md`) on top of the built-in exclusions,
    /// without touching git. Without `--import-gitignore`, an existing file
    /// is left untouched.
    #[command(after_help = "Examples:\n  cargo run -p mct-cli -- --root . ignore-init\n  cargo run -p mct-cli -- --root . ignore-init --import-gitignore")]
    IgnoreInit {
        /// Activate `@import-gitignore`, so everything the project's
        /// `.gitignore` excludes is excluded from indexing too. On a fresh
        /// file this is baked into the generated content; on an existing
        /// one, the directive is appended if it isn't already there —
        /// otherwise this is the one case `ignore-init` updates a file
        /// instead of leaving it alone.
        #[arg(long)]
        import_gitignore: bool,
    },
    /// Keep the generated index out of git.
    ///
    /// Adds `.mct-index/` to the project's `.gitignore` (creating it if
    /// needed), so the generated symbol database — fully derived from
    /// source, regenerated by `reindex` — never ends up committed. Leaves
    /// everything else already in the file untouched; a no-op if it's
    /// already covered.
    #[command(after_help = "Example:\n  cargo run -p mct-cli -- --root . gitignore-init")]
    GitignoreInit,
}

fn build_registry() -> LanguageRegistry {
    let mut registry = LanguageRegistry::new();
    registry.register(Arc::new(mct_lang_rust::RustParser));
    registry.register(Arc::new(mct_lang_python::PythonParser));
    registry.register(Arc::new(mct_lang_java::JavaParser));
    registry.register(Arc::new(mct_lang_kotlin::KotlinParser));
    registry.register(Arc::new(mct_lang_csharp::CSharpParser));
    registry.register(Arc::new(mct_lang_js_ts::JsTsParser));
    registry.register(Arc::new(mct_lang_cpp::CppParser));
    registry.register(Arc::new(mct_lang_go::GoParser));
    registry.register(Arc::new(mct_lang_html::HtmlParser));
    registry.register(Arc::new(mct_lang_css::CssParser));
    registry.register(Arc::new(mct_lang_xml::XmlParser));
    registry.register(Arc::new(mct_lang_xaml::XamlParser));
    registry.register(Arc::new(mct_lang_bash::BashParser));
    registry.register(Arc::new(mct_lang_powershell::PowerShellParser));
    registry.register(Arc::new(mct_lang_php::PhpParser));
    registry.register(Arc::new(mct_lang_md::MarkdownParser));
    registry
}

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    let root = match cli.root {
        Some(root) => root,
        None => std::env::current_dir()?,
    };

    // None of these touch the index at all, so they're handled before
    // Index::open — running them shouldn't have the side effect of creating
    // .mct-index/.
    if let Command::McpRegister { name } = cli.command {
        return mcp_register(&root, name);
    }
    if let Command::IgnoreInit { import_gitignore } = cli.command {
        return ignore_init(&root, import_gitignore);
    }
    if let Command::GitignoreInit = cli.command {
        return gitignore_init(&root);
    }

    let db_path = root.join(".mct-index").join("index.sqlite3");
    let registry = build_registry();
    let exclude = ExcludeSet::new(&mct_index::read_ignore_file(&root));
    let mut index = Index::open(&root, &db_path, exclude)?;

    match cli.command {
        Command::Init => print_reindex(index.reindex(&registry, false)?),
        Command::Reindex { force } => print_reindex(index.reindex(&registry, force)?),
        Command::Status => print_status(index.status()?),
        Command::McpRegister { .. } | Command::IgnoreInit { .. } | Command::GitignoreInit => {
            unreachable!("returned above")
        }
    }

    Ok(())
}

/// Inserts (or replaces) this project's `mct-mcp-server` entry under
/// `mcpServers` in `<root>/.mcp.json`, creating the file if it doesn't exist.
/// Any other server already configured there is left untouched — this only
/// ever writes the one key it owns.
fn mcp_register(root: &Path, name: Option<String>) -> anyhow::Result<()> {
    let root = root.canonicalize()?;
    let server_name = name.unwrap_or_else(|| {
        root.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("mct-mcp-server")
            .to_string()
    });
    let config_path = root.join(".mcp.json");

    let mut config: serde_json::Value = if config_path.exists() {
        serde_json::from_str(&std::fs::read_to_string(&config_path)?)?
    } else {
        serde_json::json!({})
    };

    let top = config
        .as_object_mut()
        .ok_or_else(|| anyhow::anyhow!("{}: top level must be a JSON object", config_path.display()))?;
    let servers = top
        .entry("mcpServers")
        .or_insert_with(|| serde_json::json!({}))
        .as_object_mut()
        .ok_or_else(|| anyhow::anyhow!("{}: \"mcpServers\" must be a JSON object", config_path.display()))?;

    servers.insert(
        server_name.clone(),
        serde_json::json!({
            "type": "stdio",
            "command": "mct-mcp-server",
            "args": ["--root", display_path(&root)],
            "env": {}
        }),
    );

    std::fs::write(&config_path, format!("{}\n", serde_json::to_string_pretty(&config)?))?;
    println!("Registered `{server_name}` in {}", display_path(&config_path));
    Ok(())
}

/// Writes a starter `.mctignore` at `root` if one doesn't already exist.
/// Never overwrites an existing file's own patterns — same non-destructive
/// stance as `mcp_register`, just without a merge target here since there's
/// nothing to merge into a plain-text ignore file.
///
/// `import_gitignore` lets the user opt into `@import-gitignore` instead of
/// hand-editing the file: on a fresh file it's baked into the generated
/// content (uncommenting the template's own example line for it); on an
/// existing one, [`activate_gitignore_import`] appends it if it isn't
/// already there — the one case this function updates rather than leaves
/// alone, gated entirely behind the flag so a plain `ignore-init` on an
/// existing file still never touches it.
fn ignore_init(root: &Path, import_gitignore: bool) -> anyhow::Result<()> {
    let path = root.join(mct_index::IGNORE_FILE_NAME);
    if path.exists() {
        if import_gitignore {
            return activate_gitignore_import(&path);
        }
        println!("{} already exists, leaving it as-is.", display_path(&path));
        return Ok(());
    }

    let contents = if import_gitignore {
        let commented = format!("# {}\n", mct_index::GITIGNORE_IMPORT_DIRECTIVE);
        let active = format!("{}\n", mct_index::GITIGNORE_IMPORT_DIRECTIVE);
        mct_index::IGNORE_FILE_TEMPLATE.replacen(&commented, &active, 1)
    } else {
        mct_index::IGNORE_FILE_TEMPLATE.to_string()
    };
    std::fs::write(&path, &contents)?;
    println!(
        "Wrote starter {}{}",
        display_path(&path),
        if import_gitignore {
            ", importing .gitignore"
        } else {
            ""
        }
    );
    Ok(())
}

/// Appends [`mct_index::GITIGNORE_IMPORT_DIRECTIVE`] to an existing
/// `.mctignore` at `path`, if it isn't already active on some line of its
/// own — idempotent, and never touches anything else already in the file.
fn activate_gitignore_import(path: &Path) -> anyhow::Result<()> {
    let contents = std::fs::read_to_string(path)?;
    if contents.lines().any(|line| line.trim() == mct_index::GITIGNORE_IMPORT_DIRECTIVE) {
        println!("{} already imports .gitignore.", display_path(path));
        return Ok(());
    }

    let mut updated = contents;
    if !updated.is_empty() && !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str(mct_index::GITIGNORE_IMPORT_DIRECTIVE);
    updated.push('\n');

    std::fs::write(path, &updated)?;
    println!(
        "Added `{}` to {}",
        mct_index::GITIGNORE_IMPORT_DIRECTIVE,
        display_path(path)
    );
    Ok(())
}

/// `.mct-index/`'s entry, appended to `.gitignore` by [`gitignore_init`].
const GITIGNORE_INDEX_ENTRY: &str = ".mct-index/";

/// Ensures `<root>/.gitignore` excludes `.mct-index/` — the generated
/// SQLite database is fully derived from source (`reindex` regenerates it
/// from nothing) and changes on every run, so committing it just bloats
/// history with a binary file nobody needs to review or merge.
///
/// Additive and idempotent, same non-destructive stance as `mcp_register`/
/// `ignore_init`: creates `.gitignore` if it doesn't exist, appends the
/// entry if no existing line already covers it, and never touches anything
/// else already there. The existing-coverage check is a plain trimmed-line
/// match, not full gitignore pattern matching — good enough to avoid
/// duplicating the exact line this function itself writes on a second run,
/// without reimplementing gitignore semantics for a single well-known path.
fn gitignore_init(root: &Path) -> anyhow::Result<()> {
    let path = root.join(".gitignore");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();

    if existing
        .lines()
        .any(|line| line.trim() == GITIGNORE_INDEX_ENTRY || line.trim() == ".mct-index")
    {
        println!("{} already excludes `.mct-index/`.", display_path(&path));
        return Ok(());
    }

    let mut updated = existing;
    if !updated.is_empty() && !updated.ends_with('\n') {
        updated.push('\n');
    }
    if !updated.is_empty() {
        updated.push('\n');
    }
    updated.push_str(
        "# mini-consumes-tokens: local symbol index, regenerated by `mct-cli reindex` — never worth committing.\n",
    );
    updated.push_str(GITIGNORE_INDEX_ENTRY);
    updated.push('\n');

    std::fs::write(&path, &updated)?;
    println!("Added `.mct-index/` to {}", display_path(&path));
    Ok(())
}

/// `Path::canonicalize` returns Windows' `\\?\`-prefixed "verbatim" form —
/// a valid Win32 path, but not what should land in a human-edited config
/// file or get passed as a plain CLI argument to a subprocess that may not
/// expect it. Strips it for display/config purposes; a no-op on any other
/// platform. `\\?\UNC\server\share` (the verbatim form of a network path)
/// needs the `UNC` segment folded back into a leading `\\`, not just the
/// `\\?\` marker dropped, or the result wouldn't be a valid UNC path.
fn display_path(path: &Path) -> String {
    let s = path.to_string_lossy().into_owned();
    if let Some(rest) = s.strip_prefix(r"\\?\UNC\") {
        format!(r"\\{rest}")
    } else if let Some(rest) = s.strip_prefix(r"\\?\") {
        rest.to_string()
    } else {
        s
    }
}

fn print_reindex(report: mct_index::ReindexReport) {
    println!(
        "Reindex complete: {} parsed, {} unchanged, {} removed, {} symbols written.",
        report.files_parsed, report.files_unchanged, report.files_removed, report.symbols_written
    );
    if !report.issues.is_empty() {
        println!("{} issue(s):", report.issues.len());
        for issue in &report.issues {
            println!("  {} [{:?}]: {}", issue.relative_path, issue.kind, issue.detail);
        }
    }
}

fn print_status(status: mct_index::IndexStatus) {
    println!(
        "{} files indexed, {} symbols total.",
        status.total_files, status.total_symbols
    );
    match status.last_indexed_at {
        Some(ts) => println!("Last indexed at unix timestamp {ts}."),
        None => println!("Never indexed yet."),
    }
    if !status.languages.is_empty() {
        println!("Coverage by language:");
        for lang in &status.languages {
            println!("  {}: {} files, {} symbols", lang.language, lang.file_count, lang.symbol_count);
        }
    }
    if !status.unsupported_languages.is_empty() {
        println!(
            "Languages seen but not yet supported: {}",
            status.unsupported_languages.join(", ")
        );
    }
    if !status.syntax_errors.is_empty() {
        println!("{} file(s) failed to parse:", status.syntax_errors.len());
        for err in &status.syntax_errors {
            println!("  {}: {}", err.relative_path, err.detail);
        }
    }
    if !status.dependencies.is_empty() {
        println!("Dependencies detected:");
        for manifest in &status.dependencies {
            println!(
                "  {} ({}, {} dep(s)):",
                manifest.manifest_path,
                manifest.language,
                manifest.dependencies.len()
            );
            for dep in &manifest.dependencies {
                match &dep.version {
                    Some(version) => println!("    {} {}", dep.name, version),
                    None => println!("    {}", dep.name),
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    // Test code: an unwrap()/expect() here means a broken test precondition,
    // and panicking is the correct behavior — this module only touches
    // temp-dir fixtures this test creates itself, never repo-input content.
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;
    use std::fs;

    fn temp_project_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("mct-cli-test-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("create temp test dir");
        dir
    }

    /// Every language this CLI must be able to index. Kept as a literal list
    /// rather than derived from `build_registry()` so that *forgetting* to
    /// add the `registry.register(...)` line here — the classic half-done
    /// language rollout, since `CONTRIBUTING.md` requires registering in two
    /// places — fails a test instead of silently shipping a CLI that skips
    /// that language while the MCP server indexes it.
    const EXPECTED_LANGUAGES: &[&str] = &[
        "bash",
        "cpp",
        "csharp",
        "css",
        "go",
        "html",
        "java",
        "javascript_typescript",
        "kotlin",
        "markdown",
        "php",
        "powershell",
        "python",
        "rust",
        "xaml",
        "xml",
    ];

    #[test]
    fn the_cli_registry_wires_in_every_shipped_language() {
        let registry = build_registry();
        let mut ids = registry.language_ids();
        ids.sort_unstable();
        let mut expected = EXPECTED_LANGUAGES.to_vec();
        expected.sort_unstable();
        assert_eq!(ids, expected);
    }

    #[test]
    fn the_cli_registry_resolves_a_representative_extension_for_each_language() {
        let registry = build_registry();
        for (extension, language) in [
            ("sh", "bash"),
            ("hpp", "cpp"),
            ("cs", "csharp"),
            ("css", "css"),
            ("go", "go"),
            ("htm", "html"),
            ("java", "java"),
            ("tsx", "javascript_typescript"),
            ("kts", "kotlin"),
            ("md", "markdown"),
            ("php", "php"),
            ("psm1", "powershell"),
            ("pyi", "python"),
            ("rs", "rust"),
            ("xaml", "xaml"),
            ("xml", "xml"),
        ] {
            let parser = registry
                .for_extension(extension)
                .unwrap_or_else(|| panic!("no parser registered for `.{extension}`"));
            assert_eq!(parser.language_id(), language, ".{extension}");
        }
        // `.lua` has a crate but is deliberately not wired in here (it is the
        // plugin-architecture proof, not a shipped language).
        assert!(registry.for_extension("lua").is_none());
    }

    #[test]
    fn a_polyglot_project_indexes_end_to_end_through_the_cli_registry() {
        let dir = temp_project_dir("polyglot-index");
        fs::write(dir.join("lib.rs"), "pub fn add(a: i32) -> i32 { a }\n").unwrap();
        fs::write(dir.join("app.py"), "def run():\n    return add(1)\n").unwrap();
        fs::write(dir.join("main.go"), "package main\n\nfunc Run() int {\n\treturn 1\n}\n").unwrap();
        fs::write(dir.join("notes.md"), "# Title\n\nbody\n").unwrap();

        let db_path = dir.join(".mct-index").join("index.sqlite3");
        let registry = build_registry();
        let mut index = Index::open(&dir, &db_path, ExcludeSet::default()).unwrap();

        let report = index.reindex(&registry, false).unwrap();
        assert_eq!(report.files_parsed, 4, "{:?}", report.issues);
        assert!(report.issues.is_empty(), "{:?}", report.issues);

        let status = index.status().unwrap();
        let mut languages: Vec<&str> = status.languages.iter().map(|l| l.language.as_str()).collect();
        languages.sort_unstable();
        assert_eq!(languages, vec!["go", "markdown", "python", "rust"]);
        assert_eq!(index.find_symbol("add").unwrap().len(), 1);

        // A second run over an untouched tree re-parses nothing, and the
        // on-disk database survives being reopened.
        drop(index);
        let mut index = Index::open(&dir, &db_path, ExcludeSet::default()).unwrap();
        let second = index.reindex(&registry, false).unwrap();
        assert_eq!(second.files_parsed, 0);
        assert_eq!(second.files_unchanged, 4);
        assert_eq!(index.status().unwrap().total_symbols, status.total_symbols);

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn mcp_register_creates_new_config() {
        let dir = temp_project_dir("new");

        mcp_register(&dir, Some("my-server".to_string())).expect("register should succeed");

        let contents = fs::read_to_string(dir.join(".mcp.json")).expect("config should exist");
        let json: serde_json::Value = serde_json::from_str(&contents).expect("valid json");
        assert_eq!(json["mcpServers"]["my-server"]["command"], "mct-mcp-server");
        assert_eq!(json["mcpServers"]["my-server"]["type"], "stdio");

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn mcp_register_preserves_other_servers_and_is_idempotent() {
        let dir = temp_project_dir("merge");
        fs::write(
            dir.join(".mcp.json"),
            r#"{"mcpServers":{"other-tool":{"type":"stdio","command":"other-tool"}}}"#,
        )
        .expect("seed existing config");

        mcp_register(&dir, Some("mine".to_string())).expect("first register should succeed");
        mcp_register(&dir, Some("mine".to_string())).expect("second register should succeed");

        let contents = fs::read_to_string(dir.join(".mcp.json")).expect("config should exist");
        let json: serde_json::Value = serde_json::from_str(&contents).expect("valid json");
        assert_eq!(json["mcpServers"]["other-tool"]["command"], "other-tool");
        assert_eq!(json["mcpServers"]["mine"]["command"], "mct-mcp-server");
        assert_eq!(json["mcpServers"].as_object().unwrap().len(), 2);

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn mcp_register_strips_windows_verbatim_path_prefix() {
        let dir = temp_project_dir("verbatim-path");

        mcp_register(&dir, Some("my-server".to_string())).expect("register should succeed");

        let contents = fs::read_to_string(dir.join(".mcp.json")).expect("config should exist");
        assert!(
            !contents.contains(r"\\?\"),
            "config should not contain the Windows verbatim-path prefix, got: {contents}"
        );

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn ignore_init_creates_starter_file() {
        let dir = temp_project_dir("ignore-init-new");

        ignore_init(&dir, false).expect("ignore_init should succeed");

        let contents = fs::read_to_string(dir.join(mct_index::IGNORE_FILE_NAME)).expect("file should exist");
        assert_eq!(contents, mct_index::IGNORE_FILE_TEMPLATE);

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn ignore_init_does_not_overwrite_an_existing_file() {
        let dir = temp_project_dir("ignore-init-existing");
        fs::write(dir.join(mct_index::IGNORE_FILE_NAME), "*.md\n").expect("seed existing ignore file");

        ignore_init(&dir, false).expect("ignore_init should succeed");

        let contents = fs::read_to_string(dir.join(mct_index::IGNORE_FILE_NAME)).expect("file should exist");
        assert_eq!(contents, "*.md\n");

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn ignore_init_with_import_gitignore_activates_the_directive() {
        let dir = temp_project_dir("ignore-init-import-gitignore");

        ignore_init(&dir, true).expect("ignore_init should succeed");

        let contents = fs::read_to_string(dir.join(mct_index::IGNORE_FILE_NAME)).expect("file should exist");
        assert!(
            contents.lines().any(|line| line == mct_index::GITIGNORE_IMPORT_DIRECTIVE),
            "expected an active (uncommented) directive line, got: {contents}"
        );
        assert_eq!(
            mct_index::read_ignore_file(&dir),
            Vec::<String>::new(),
            "the directive alone (no other patterns, no .gitignore yet) should add nothing"
        );

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn ignore_init_without_the_flag_never_touches_an_existing_file() {
        let dir = temp_project_dir("ignore-init-no-flag-existing");
        fs::write(dir.join(mct_index::IGNORE_FILE_NAME), "*.md\n").expect("seed existing ignore file");

        ignore_init(&dir, false).expect("ignore_init should succeed");

        let contents = fs::read_to_string(dir.join(mct_index::IGNORE_FILE_NAME)).expect("file should exist");
        assert_eq!(contents, "*.md\n");

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn ignore_init_import_gitignore_flag_activates_the_directive_on_an_existing_file() {
        let dir = temp_project_dir("ignore-init-import-gitignore-existing");
        fs::write(dir.join(mct_index::IGNORE_FILE_NAME), "*.md\n").expect("seed existing ignore file");

        ignore_init(&dir, true).expect("ignore_init should succeed");

        let contents = fs::read_to_string(dir.join(mct_index::IGNORE_FILE_NAME)).expect("file should exist");
        assert_eq!(contents, "*.md\n@import-gitignore\n");

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn ignore_init_import_gitignore_flag_is_idempotent_on_an_existing_file() {
        let dir = temp_project_dir("ignore-init-import-gitignore-idempotent");
        fs::write(dir.join(mct_index::IGNORE_FILE_NAME), "*.md\n").expect("seed existing ignore file");

        ignore_init(&dir, true).expect("first ignore_init should succeed");
        let first = fs::read_to_string(dir.join(mct_index::IGNORE_FILE_NAME)).expect("file should exist");
        ignore_init(&dir, true).expect("second ignore_init should succeed");
        let second = fs::read_to_string(dir.join(mct_index::IGNORE_FILE_NAME)).expect("file should exist");

        assert_eq!(first, second, "a second run should not duplicate the directive");

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gitignore_init_creates_a_new_gitignore_excluding_the_index() {
        let dir = temp_project_dir("gitignore-init-new");

        gitignore_init(&dir).expect("gitignore_init should succeed");

        let contents = fs::read_to_string(dir.join(".gitignore")).expect("file should exist");
        assert!(
            contents.lines().any(|line| line.trim() == ".mct-index/"),
            "expected `.mct-index/` in: {contents}"
        );

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gitignore_init_appends_to_an_existing_gitignore_without_disturbing_it() {
        let dir = temp_project_dir("gitignore-init-append");
        fs::write(dir.join(".gitignore"), "node_modules/\n").expect("seed existing gitignore");

        gitignore_init(&dir).expect("gitignore_init should succeed");

        let contents = fs::read_to_string(dir.join(".gitignore")).expect("file should exist");
        assert!(contents.contains("node_modules/"), "existing entry should survive: {contents}");
        assert!(
            contents.lines().any(|line| line.trim() == ".mct-index/"),
            "expected `.mct-index/` appended, got: {contents}"
        );

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gitignore_init_is_idempotent() {
        let dir = temp_project_dir("gitignore-init-idempotent");

        gitignore_init(&dir).expect("first gitignore_init should succeed");
        let first = fs::read_to_string(dir.join(".gitignore")).expect("file should exist");
        gitignore_init(&dir).expect("second gitignore_init should succeed");
        let second = fs::read_to_string(dir.join(".gitignore")).expect("file should exist");

        assert_eq!(first, second, "a second run should not duplicate the entry");

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gitignore_init_recognizes_an_already_present_entry() {
        let dir = temp_project_dir("gitignore-init-already-present");
        fs::write(dir.join(".gitignore"), "target/\n.mct-index/\n").expect("seed existing gitignore");

        gitignore_init(&dir).expect("gitignore_init should succeed");

        let contents = fs::read_to_string(dir.join(".gitignore")).expect("file should exist");
        assert_eq!(contents, "target/\n.mct-index/\n", "should not add a duplicate entry");

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_mctignore_pattern_keeps_matching_files_out_of_the_index() {
        let dir = temp_project_dir("mctignore-excludes");
        fs::write(dir.join("lib.rs"), "pub fn add(a: i32) -> i32 { a }\n").unwrap();
        fs::write(dir.join("NOTES.md"), "# notes\n").unwrap();
        fs::write(dir.join(mct_index::IGNORE_FILE_NAME), "*.md\n").unwrap();

        let db_path = dir.join(".mct-index").join("index.sqlite3");
        let registry = build_registry();
        let exclude = ExcludeSet::new(&mct_index::read_ignore_file(&dir));
        let mut index = Index::open(&dir, &db_path, exclude).unwrap();

        let report = index.reindex(&registry, false).unwrap();
        assert_eq!(report.files_parsed, 1, "{:?}", report.issues);

        let status = index.status().unwrap();
        let languages: Vec<&str> = status.languages.iter().map(|l| l.language.as_str()).collect();
        assert_eq!(languages, vec!["rust"]);

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn mcp_register_defaults_name_to_root_directory_name() {
        let dir = temp_project_dir("default-name");

        mcp_register(&dir, None).expect("register should succeed");

        let contents = fs::read_to_string(dir.join(".mcp.json")).expect("config should exist");
        let json: serde_json::Value = serde_json::from_str(&contents).expect("valid json");
        let expected_name = dir.canonicalize().unwrap().file_name().unwrap().to_string_lossy().to_string();
        assert!(json["mcpServers"].as_object().unwrap().contains_key(&expected_name));

        fs::remove_dir_all(&dir).ok();
    }
}
